In [12]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

iris.csv



In [13]:
##!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 20 23:48:47 2017

@author: akashsrivastava
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from keras.utils import to_categorical


#os.chdir('/Users/akashsrivastava/Desktop/MachineLearning/kaggle/iris-keras')

dataset = pd.read_csv('../input/iris.csv')

dataset.head()

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0           0                5.1               3.5                1.4   
1           1                4.9               3.0                1.4   
2           2                4.7               3.2                1.3   
3           3                4.6               3.1                1.5   
4           4                5.0               3.6                1.4   

   petal width (cm)  target  
0               0.2       0  
1               0.2       0  
2               0.2       0  
3               0.2       0  
4               0.2       0

In [14]:
#Splitting the data into training and test test
X = dataset.iloc[:,1:5].values
y = dataset.iloc[:,5].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [15]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [16]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(10,input_shape=(4,),activation='tanh'))
model.add(Dense(8,activation='tanh'))
model.add(Dense(6,activation='tanh'))
model.add(Dense(3,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_11 (Dense)             (None, 6)                 54        
_________________________________________________________________
dense_12 (Dense)             (None, 3)                 21        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [17]:
#fitting the model and predicting 
history = model.fit(X_train,y_train,epochs=100,validation_split=0.2)
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Train on 96 samples, validate on 24 samples
Epoch 1/100
96/96 [==============================] - 0s 5ms/step - loss: 1.0161 - acc: 0.5208 - val_loss: 0.9602 - val_acc: 0.5417
Epoch 2/100
96/96 [==============================] - 0s 85us/step - loss: 0.6860 - acc: 0.7292 - val_loss: 0.7091 - val_acc: 0.5417
Epoch 3/100
96/96 [==============================] - 0s 67us/step - loss: 0.5306 - acc: 0.7292 - val_loss: 0.5824 - val_acc: 0.5417
Epoch 4/100
96/96 [==============================] - 0s 78us/step - loss: 0.4680 - acc: 0.7604 - val_loss: 0.4907 - val_acc: 0.8750
Epoch 5/100
96/96 [==============================] - 0s 71us/step - loss: 0.4096 - acc: 0.9688 - val_loss: 0.4280 - val_acc: 0.8750
Epoch 6/100
96/96 [==============================] - 0s 81us/step - loss: 0.3329 - acc: 0.9688 - val_loss: 0.4431 - val_acc: 0.7917
Epoch 7/100
96/96 [==============================] - 0s 70us/step - loss: 0.2699 - acc: 0.9375 - val_loss: 0.3417 - val_acc: 0.9583
Epoch 8/100
96/96 [==============

96/96 [==============================] - 0s 75us/step - loss: 0.0534 - acc: 0.9896 - val_loss: 0.0249 - val_acc: 1.0000
Epoch 63/100
96/96 [==============================] - 0s 74us/step - loss: 0.0858 - acc: 0.9583 - val_loss: 0.1786 - val_acc: 0.8750
Epoch 64/100
96/96 [==============================] - 0s 71us/step - loss: 0.1017 - acc: 0.9688 - val_loss: 0.3619 - val_acc: 0.8750
Epoch 65/100
96/96 [==============================] - 0s 85us/step - loss: 0.0544 - acc: 0.9792 - val_loss: 0.0460 - val_acc: 1.0000
Epoch 66/100
96/96 [==============================] - 0s 84us/step - loss: 0.0667 - acc: 0.9792 - val_loss: 0.0721 - val_acc: 0.9583
Epoch 67/100
96/96 [==============================] - 0s 80us/step - loss: 0.0577 - acc: 0.9792 - val_loss: 0.1546 - val_acc: 0.9167
Epoch 68/100
96/96 [==============================] - 0s 75us/step - loss: 0.0636 - acc: 0.9792 - val_loss: 0.3081 - val_acc: 0.8750
Epoch 69/100
96/96 [==============================] - 0s 73us/step - loss: 0.0651 

In [18]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
